name: On Push
on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    timeout-minutes: 10
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - run: npm ci
      - run: npm run build
      - name: Maybe make release
        run: npm run semantic-release || true
        env:
          GITHUB_TOKEN: ${{ github.token }}

